// Demo for tail recursive variant of 
//   node_t* list_remove_tail(node_t* node);

#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>

#include "singleLinkedIntList_type.h"

extern node_t* list_insert_end(node_t* anchor, int data);
extern node_t* list_remove_tail(node_t* node);
extern void list_dump(node_t *anchor);

// ----------------------------------------------------------------
// MAIN
// ----------------------------------------------------------------

int main () {
  node_t* mylist=NULL;

  printf("\nDemo 8: deleting at the end\n");

  // Insert at the tail
  mylist = list_insert_end(mylist, 10);
  mylist = list_insert_end(mylist, 11);
  mylist = list_insert_end(mylist, 12);
  mylist = list_insert_end(mylist, 13);

  // Dump the list
  printf("\nList generated by list_insert_end:\n");
  list_dump(mylist);
  printf("\n");

  printf("Remove elements at the end until list is empty:\n\n");
  while (mylist != NULL){
    mylist = list_remove_tail(mylist);
    list_dump(mylist);
    printf("\n");
  }
  printf("The list is empty, now\n");

  return EXIT_SUCCESS;
}
