// Demo for unsorted single linked list of integers: functional version
// NOTE:
// selection of iterative or recursive version is solely made by linking
// the appropriate object files
//

#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>

#include "singleLinkedIntList_type.h"

extern node_t* list_create_node(int data);
extern node_t* list_insert_end(node_t* anchor, int data);
extern node_t* list_insert_end_V1(node_t* node, int data);
extern node_t* list_insert_end_iter(node_t* anchor, int data);

extern void list_dump(node_t *anchor);
extern node_t* list_free(node_t* anchor);

// ----------------------------------------------------------------
// MAIN
// ----------------------------------------------------------------

int main () {
  node_t* mylist=NULL;

  // ---------------------------------------
  // Demo 2: insert at the end
  printf("\nDemo 2\n");
  mylist = list_insert_end(mylist, 10);
  mylist = list_insert_end(mylist, 11);
  mylist = list_insert_end(mylist, 12);
  mylist = list_insert_end(mylist, 13);
  mylist = list_insert_end(mylist, 14);
  mylist = list_insert_end(mylist, 15);

  // Dump the list
  printf("List generated by list_insert_end\n");
  list_dump(mylist);

  // Free the list; assignment sets anchor to NULL
  mylist = list_free(mylist);

  // ---------------------------------------
  return EXIT_SUCCESS;
}
